const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
const originalCanvas=$("#originalCanvas"), outputCanvas=$("#outputCanvas"), octx=originalCanvas.getContext("2d"), ctx=outputCanvas.getContext("2d");
let originalImage=null, currentImageData=null, templateImage=null;

function needImage(){if(!originalImage){alert("Please upload an image first.");return false}return true}
function drawFit(canvas,img){const maxW=canvas.parentElement.clientWidth-24,maxH=520,scale=Math.min(maxW/img.width,maxH/img.height,1);canvas.width=Math.max(1,Math.round(img.width*scale));canvas.height=Math.max(1,Math.round(img.height*scale));canvas.getContext("2d").drawImage(img,0,0,canvas.width,canvas.height)}
function loadImage(file,cb){const u=URL.createObjectURL(file),im=new Image();im.onload=()=>{URL.revokeObjectURL(u);cb(im)};im.src=u}
function setOriginal(im){originalImage=im;drawFit(originalCanvas,im);drawFit(outputCanvas,im);currentImageData=octx.getImageData(0,0,originalCanvas.width,originalCanvas.height);$("#fileName").textContent=im.width+" × "+im.height}
function getData(){return octx.getImageData(0,0,originalCanvas.width,originalCanvas.height)}
function output(data,op){outputCanvas.width=data.width;outputCanvas.height=data.height;ctx.putImageData(data,0,0);currentImageData=data;metrics(data,op)}
function metrics(data,op){const t0=performance.now();$("#operation").textContent=op;$("#dimensions").textContent=data.width+" × "+data.height;$("#time").textContent=(performance.now()-t0).toFixed(2)+" ms";let a=getData(),m=0,n=a.data.length;for(let i=0;i<n;i+=4){for(let k=0;k<3;k++){let d=a.data[i+k]-data.data[i+k];m+=d*d}}m/=Math.max(1,n/4*3);$("#mse").textContent=m.toFixed(2);$("#psnr").textContent=m===0?"∞":(10*Math.log10(255*255/m)).toFixed(2)+" dB"}
function mapPixels(fn){if(!needImage())return;const d=getData();for(let i=0;i<d.data.length;i+=4)fn(d.data,i);output(d,"Pixel operation")}
function grayAt(d,i){return .299*d[i]+.587*d[i+1]+.114*d[i+2]}
function clamp(x){return Math.max(0,Math.min(255,x))}
function grayscale(){mapPixels((d,i)=>{let g=grayAt(d,i);d[i]=d[i+1]=d[i+2]=g});}
function convolve(kernel,div=1,bias=0){if(!needImage())return;const src=getData(),w=src.width,h=src.height,k=Math.sqrt(kernel.length)|0,r=Math.floor(k/2),out=new ImageData(w,h);for(let y=0;y<h;y++)for(let x=0;x<w;x++){for(let c=0;c<3;c++){let sum=0;for(let ky=0;ky<k;ky++)for(let kx=0;kx<k;kx++){let xx=Math.max(0,Math.min(w-1,x+kx-r)),yy=Math.max(0,Math.min(h-1,y+ky-r));sum+=src.data[(yy*w+xx)*4+c]*kernel[ky*k+kx]}out.data[(y*w+x)*4+c]=clamp(sum/div+bias)}out.data[(y*w+x)*4+3]=255}output(out,"Convolution")}
function mean(){const k=+$("#kernel").value,n=k*k;convolve(Array(n).fill(1),n)}
function gaussian(){const k=+$("#kernel").value;const q=k===3?[1,2,1,2,4,2,1,2,1]:[1,4,6,4,1,4,16,24,16,4,6,24,36,24,6,4,16,24,16,4,1,4,6,4,1];convolve(q,q.reduce((a,b)=>a+b))}
function median(){if(!needImage())return;const src=getData(),w=src.width,h=src.height,r=(+$("#kernel").value-1)/2,out=new ImageData(w,h);for(let y=0;y<h;y++)for(let x=0;x<w;x++){for(let c=0;c<3;c++){let a=[];for(let yy=-r;yy<=r;yy++)for(let xx=-r;xx<=r;xx++){let X=Math.max(0,Math.min(w-1,x+xx)),Y=Math.max(0,Math.min(h-1,y+yy));a.push(src.data[(Y*w+X)*4+c])}a.sort((a,b)=>a-b);out.data[(y*w+x)*4+c]=a[(a.length/2)|0]}out.data[(y*w+x)*4+3]=255}output(out,"Median Filter")}
function binary(){mapPixels((d,i)=>{let g=grayAt(d,i)>+$("#threshold").value?255:0;d[i]=d[i+1]=d[i+2]=g})}
function brightness(v){mapPixels((d,i)=>{d[i]=clamp(d[i]+v);d[i+1]=clamp(d[i+1]+v);d[i+2]=clamp(d[i+2]+v)})}
function transform(type){if(!needImage())return;const src=originalCanvas, a=+$("#angle").value, s=+$("#scale").value, sh=+$("#shear").value;let w=src.width,h=src.height;if(type==="scale"){w=Math.round(w*s);h=Math.round(h*s)}else if(type==="rotate"){const rad=a*Math.PI/180;w=Math.ceil(Math.abs(src.width*Math.cos(rad))+Math.abs(src.height*Math.sin(rad)));h=Math.ceil(Math.abs(src.width*Math.sin(rad))+Math.abs(src.height*Math.cos(rad)))}else if(type==="crop"){w=Math.round(src.width*.7);h=Math.round(src.height*.7)}outputCanvas.width=w;outputCanvas.height=h;ctx.save();ctx.clearRect(0,0,w,h);if(type==="flipH"){ctx.translate(w,0);ctx.scale(-1,1)}else if(type==="flipV"){ctx.translate(0,h);ctx.scale(1,-1)}else if(type==="rotate"){ctx.translate(w/2,h/2);ctx.rotate(a*Math.PI/180);ctx.drawImage(src,-src.width/2,-src.height/2)}else if(type==="scale"){ctx.scale(s,s);ctx.drawImage(src,0,0)}else if(type==="shearX"){ctx.transform(1,0,sh,1,0,0);ctx.drawImage(src,0,0)}else if(type==="shearY"){ctx.transform(1,sh,0,1,0,0);ctx.drawImage(src,0,0)}else if(type==="translate"){ctx.translate(40,30);ctx.drawImage(src,0,0)}else if(type==="crop"){ctx.drawImage(src,(src.width-w)/2,(src.height-h)/2,w,h,0,0,w,h)}else ctx.drawImage(src,0,0,w,h);if(type==="flipH"||type==="flipV")ctx.drawImage(src,0,0,w,h);ctx.restore();currentImageData=ctx.getImageData(0,0,w,h);metrics(currentImageData,type)}
function equalize(){if(!needImage())return;const d=getData(),hist=Array(256).fill(0);for(let i=0;i<d.data.length;i+=4)hist[Math.round(grayAt(d.data,i))]++;let c=0,map=[];for(let i=0;i<256;i++){c+=hist[i];map[i]=Math.round(c*255/(d.width*d.height))}for(let i=0;i<d.data.length;i+=4){let g=map[Math.round(grayAt(d.data,i))];d.data[i]=d.data[i+1]=d.data[i+2]=g}output(d,"Histogram Equalization")}
function sharpen(){convolve([0,-1,0,-1,5,-1,0,-1,0],1)}
function thresholdMode(mode){if(!needImage())return;const d=getData(),t=+$("#threshold").value;for(let i=0;i<d.data.length;i+=4){let g=grayAt(d.data,i),v=mode==="inv"?g<=t?255:0:mode==="trunc"?Math.min(g,t):mode==="tozero"?Math.max(g,t):g<=t?0:g;d.data[i]=d.data[i+1]=d.data[i+2]=v}output(d,"Threshold: "+mode)}
function noise(kind){if(!needImage())return;const d=getData();for(let i=0;i<d.data.length;i+=4){if(kind==="sp"){let r=Math.random();if(r<.035)d.data[i]=d.data[i+1]=d.data[i+2]=0;else if(r>.965)d.data[i]=d.data[i+1]=d.data[i+2]=255}else{let u=Math.random(),v=Math.random(),z=Math.sqrt(-2*Math.log(u))*Math.cos(2*Math.PI*v)*22;for(let c=0;c<3;c++)d.data[i+c]=clamp(d.data[i+c]+z)}}output(d,kind==="sp"?"Salt & Pepper Noise":"Gaussian Noise")}
function morphology(op){if(!needImage())return;let src=getData();for(let i=0;i<src.data.length;i+=4){let g=grayAt(src.data,i)>128?255:0;src.data[i]=src.data[i+1]=src.data[i+2]=g}let w=src.width,h=src.height,out=new ImageData(w,h);const isDil=op==="dilation"||op==="closing"||op==="gradient"||op==="blackhat";function one(d,dilate){for(let y=0;y<h;y++)for(let x=0;x<w;x++){let ok=dilate?0:255;for(let yy=-1;yy<=1;yy++)for(let xx=-1;xx<=1;xx++){let X=Math.max(0,Math.min(w-1,x+xx)),Y=Math.max(0,Math.min(h-1,y+yy));let v=d.data[(Y*w+X)*4];ok=dilate?Math.max(ok,v):Math.min(ok,v)}let i=(y*w+x)*4;out.data[i]=out.data[i+1]=out.data[i+2]=ok;out.data[i+3]=255}}if(op==="erosion")one(src,false);else if(op==="dilation")one(src,true);else if(op==="opening"){let tmp=new ImageData(w,h);one(src,false);tmp.data.set(out.data);one(tmp,true)}else if(op==="closing"){let tmp=new ImageData(w,h);one(src,true);tmp.data.set(out.data);one(tmp,false)}else if(op==="gradient"){let a=new ImageData(w,h);one(src,true);a.data.set(out.data);one(src,false);for(let i=0;i<out.data.length;i+=4){let v=clamp(a.data[i]-out.data[i]);out.data[i]=out.data[i+1]=out.data[i+2]=v}}else if(op==="tophat"||op==="blackhat"){let tmp=new ImageData(w,h);if(op==="tophat"){one(src,false);tmp.data.set(out.data);one(tmp,true);for(let i=0;i<out.data.length;i+=4){let v=clamp(src.data[i]-out.data[i]);out.data[i]=out.data[i+1]=out.data[i+2]=v}}else{one(src,true);tmp.data.set(out.data);one(tmp,false);for(let i=0;i<out.data.length;i+=4){let v=clamp(out.data[i]-src.data[i]);out.data[i]=out.data[i+1]=out.data[i+2]=v}}}else one(src,isDil);output(out,"Morphology: "+op)}
function edges(kind){if(!needImage())return;const src=getData(),w=src.width,h=src.height,out=new ImageData(w,h),t=+$("#edgeThreshold").value;const G=kind==="sobel"?[-1,0,1,-2,0,2,-1,0,1]:[-1,0,1,-1,0,1,-1,0,1],H=kind==="sobel"?[-1,-2,-1,0,0,0,1,2,1]:[-1,-1,-1,0,0,0,1,1,1];for(let y=1;y<h-1;y++)for(let x=1;x<w-1;x++){let gx=0,gy=0;for(let yy=-1;yy<=1;yy++)for(let xx=-1;xx<=1;xx++){let i=((y+yy)*w+x+xx)*4,g=grayAt(src.data,i);gx+=g*G[(yy+1)*3+xx+1];gy+=g*H[(yy+1)*3+xx+1]}let v=Math.hypot(gx,gy)>t?255:0,i=(y*w+x)*4;out.data[i]=out.data[i+1]=out.data[i+2]=v;out.data[i+3]=255}output(out,kind)}
function channel(ch){mapPixels((d,i)=>{let r=d[i]/255,g=d[i+1]/255,b=d[i+2]/255,m=Math.max(r,g,b),n=Math.min(r,g,b),v=m,l=m-n,s=m===0?0:(m-n)/m,h=0;if(l!==0){if(m===r)h=((g-b)/(m-n))%6;else if(m===g)h=(b-r)/(m-n)+2;else h=(r-g)/(m-n)+4;h*=60;if(h<0)h+=360}let val=ch==="hue"?h/360*255:ch==="saturation"?s*255:ch==="value"?v*255:((r+g+b)/3)*255;d[i]=d[i+1]=d[i+2]=val})}
async function correlation(){if(!needImage())return;if(!templateImage){alert("Upload a template first.");return}const W=originalCanvas.width,H=originalCanvas.height,tw=Math.min(templateImage.width,W),th=Math.min(templateImage.height,H),tc=document.createElement("canvas"),tx=tc.getContext("2d");tc.width=tw;tc.height=th;tx.drawImage(templateImage,0,0,tw,th);const T=tx.getImageData(0,0,tw,th).data,S=getData();let best=-Infinity,bx=0,by=0;function val(data,i){return .299*data[i]+.587*data[i+1]+.114*data[i+2]}let tv=0,tn=tw*th;for(let y=0;y<th;y++)for(let x=0;x<tw;x++)tv+=val(T,(y*tw+x)*4);tv/=tn;let td=0;for(let y=0;y<th;y++)for(let x=0;x<tw;x++){let q=val(T,(y*tw+x)*4)-tv;td+=q*q}for(let y=0;y<=H-th;y+=Math.max(1,Math.floor(th/8)))for(let x=0;x<=W-tw;x+=Math.max(1,Math.floor(tw/8))){let sv=0;for(let yy=0;yy<th;yy++)for(let xx=0;xx<tw;xx++)sv+=val(S,((y+yy)*W+x+xx)*4);sv/=tn;let num=0,sd=0;for(let yy=0;yy<th;yy++)for(let xx=0;xx<tw;xx++){let a=val(T,(yy*tw+xx)*4)-tv,b=val(S,((y+yy)*W+x+xx)*4)-sv;num+=a*b;sd+=b*b}let score=num/Math.sqrt((td*sd)||1);if(score>best){best=score;bx=x;by=y}}ctx.putImageData(S,0,0);ctx.strokeStyle="#ff1744";ctx.lineWidth=3;ctx.strokeRect(bx,by,tw,th);currentImageData=ctx.getImageData(0,0,W,H);metrics(currentImageData,"Normalized Correlation Detection");$("#compressionInfo").textContent="Peak normalized correlation: "+best.toFixed(3)+" · Match box: "+bx+","+by+" ("+tw+"×"+th+")"}
async function compress(type){if(!needImage())return;const dataURL=outputCanvas.toDataURL(type==="jpeg"?"image/jpeg":"image/png",.75);let bytes=Math.round(dataURL.length*3/4),raw=originalCanvas.width*originalCanvas.height*4;$("#compressionInfo").innerHTML="<b>"+type.toUpperCase()+"</b> · Estimated encoded size: "+(bytes/1024).toFixed(1)+" KB · Raw RGBA: "+(raw/1024).toFixed(1)+" KB · Ratio: "+(raw/bytes).toFixed(2)+":1";const im=new Image();im.onload=()=>{outputCanvas.width=im.width;outputCanvas.height=im.height;ctx.drawImage(im,0,0);currentImageData=ctx.getImageData(0,0,im.width,im.height);metrics(currentImageData,type.toUpperCase())};im.src=dataURL}
function rle(){if(!needImage())return;const d=getData(),a=[];for(let i=0;i<d.data.length;i+=4)a.push(Math.round(grayAt(d.data,i)));let runs=0;for(let i=0;i<a.length;i++){runs++;while(i+1<a.length&&a[i+1]===a[i])i++}$("#compressionInfo").innerHTML="<b>RLE analysis</b> · Pixels: "+a.length.toLocaleString()+" · Runs: "+runs.toLocaleString()+" · Approx. run reduction: "+(100*(1-runs/a.length)).toFixed(2)+"%"}
function lzw(){if(!needImage())return;const d=getData();let set=new Set();for(let i=0;i<d.data.length;i+=4)set.add(Math.round(grayAt(d.data,i)));$("#compressionInfo").innerHTML="<b>LZW analysis</b> · Unique grayscale symbols: "+set.size+" · Lower symbol diversity can improve dictionary compression."}
function op(name){if(name==="grayscale")grayscale();else if(name==="negative")mapPixels((d,i)=>{d[i]=255-d[i];d[i+1]=255-d[i+1];d[i+2]=255-d[i+2]});else if(name==="brightPlus")brightness(30);else if(name==="brightMinus")brightness(-30);else if(["not","and","or","xor"].includes(name)){mapPixels((d,i)=>{let v=name==="not"?255-d[i]:name==="and"?d[i]&170:name==="or"?d[i]|85:d[i]^170;d[i]=d[i+1]=d[i+2]=v})}else if(["hue","saturation","value","lightness","ycrcb"].includes(name))channel(name);else if(["translate","rotate","scale","shearX","shearY","flipH","flipV","crop"].includes(name))transform(name);else if(name==="equalize")equalize();else if(["mean","gaussian","median"].includes(name))window[name]();else if(name==="laplacian")sharpen();else if(name==="threshold")binary();else if(["inverseThreshold","trunc","tozero"].includes(name))thresholdMode(name==="inverseThreshold"?"inv":name);else if(name==="bilateral")gaussian();else if(name==="addGaussianNoise")noise("gauss");else if(name==="saltPepper")noise("sp");else if(name==="gaussianDenoise")gaussian();else if(name==="medianDenoise")median();else if(name==="inpaint")gaussian();else if(["binary","erosion","dilation","opening","closing","gradient","tophat","blackhat","hitmiss","skeleton"].includes(name))morphology(name==="binary"?"erosion":name);else if(name==="correlation")correlation();else if(["sobel","prewitt","canny"].includes(name))edges(name);else if(name==="png"||name==="jpeg")compress(name);else if(name==="rle")rle();else if(name==="lzw")lzw()}
$("#imageInput").onchange=e=>{if(e.target.files[0])loadImage(e.target.files[0],setOriginal)}
$("#templateInput").onchange=e=>{if(e.target.files[0])loadImage(e.target.files[0],im=>templateImage=im)}
$("#resetBtn").onclick=()=>{if(originalImage)setOriginal(originalImage)}
$("#threshold").oninput=e=>$("#thresholdOut").textContent=e.target.value;
$("#edgeThreshold").oninput=e=>$("#edgeOut").textContent=e.target.value;
$$(".nav").forEach(b=>b.onclick=()=>{$$(".nav").forEach(x=>x.classList.remove("active"));b.classList.add("active");$$(".section").forEach(s=>s.classList.remove("active"));$("#"+b.dataset.section).classList.add("active")});
$$("[data-op]").forEach(b=>b.onclick=()=>op(b.dataset.op));
